# Generated by Django 4.2.3 on 2023-07-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_bookedseats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedseats',
            old_name='boooking_id',
            new_name='boooking',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='train_id',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
