# Generated by Django 4.2.3 on 2023-07-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_bookedseats_bookedseat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedseat',
            old_name='boooking',
            new_name='booking',
        ),
    ]
